import { describe, expect, it } from 'vitest';
import legacyRun from './fixtures/legacy-steps.json' with { type: 'json' };
import { compileWorkout } from '../src/compile-workout';
import { SEED_EXERCISES } from '../src/seed/exercises';
import { KETTLEBELL_AND_MAT } from '../src/seed/kettlebell-and-mat';
import type { Step } from '../src/types';

/**
 * Proves the rewrite did not quietly change the workout.
 *
 * `test/fixtures/legacy-steps.json` is generated by running the original
 * single-file app's own `buildWorkout(0)` — see
 * `scripts/extract-legacy-steps.mjs`. Every step it produced must still be
 * produced, in the same order, with the same timings and wording.
 *
 * Two fields are left out of the bulk comparison because a break step's values
 * are fixed by its type and never read: `label` (only working steps are looked
 * up by the "Next: …" scan, so the old app left it unset on rests and preps)
 * and `title` (always "Rest" or "Get ready"), which is the deviation below.
 *
 * There is one deliberate difference, asserted explicitly at the bottom: the
 * fifteen-second break before the endurance section used to be a `rest` tacked
 * onto strength, and is now endurance's own `prep`. Both compilers treat prep
 * and rest identically, so the comparison below folds them into one `break`
 * kind and normalises the spoken opener.
 */

interface LegacyStep {
  sec: number;
  phase: string;
  type: string;
  title: string;
  sub?: string;
  hint?: string;
  round?: string;
  dur?: number;
  est?: number;
  tasks?: string[];
  details?: { name: string; desc: string }[];
  lbl?: string;
  say?: string;
  nextText?: string;
}

interface LegacyRun {
  steps: LegacyStep[];
  cum: number[];
  total: number;
  segs: { phase: string; start: number; total: number }[];
}

const legacy = legacyRun as LegacyRun;

const isBreak = (type: string) => type === 'rest' || type === 'prep';

/** Drop the "Rest." / "Get ready." opener, which is the one thing that moved. */
const spokenBody = (say: string) => say.replace(/^(Rest|Get ready)\.\s*/, '');

interface Comparable {
  sectionIndex: number;
  phase: string;
  kind: string;
  title: string;
  sub: string;
  hint: string;
  round: string;
  durationSec: number | undefined;
  estimatedSec: number | undefined;
  tasks: string[];
  details: string[];
  label: string;
  speech: string;
  nextText: string;
}

function fromLegacy(s: LegacyStep): Comparable {
  return {
    sectionIndex: s.sec,
    phase: s.phase,
    kind: isBreak(s.type) ? 'break' : s.type,
    title: isBreak(s.type) ? '' : s.title,
    sub: s.sub ?? '',
    hint: s.hint ?? '',
    round: s.round ?? '',
    durationSec: s.dur,
    estimatedSec: s.est,
    tasks: s.tasks ?? [],
    details: (s.details ?? []).map((d) => d.name),
    label: isBreak(s.type) ? '' : (s.lbl ?? ''),
    speech: isBreak(s.type) ? spokenBody(s.say ?? '') : (s.say ?? ''),
    nextText: s.nextText ?? '',
  };
}

function fromCompiled(s: Step): Comparable {
  return {
    sectionIndex: s.sectionIndex,
    phase: s.phase,
    kind: isBreak(s.type) ? 'break' : s.type,
    title: isBreak(s.type) ? '' : s.title,
    sub: s.sub ?? '',
    hint: s.hint ?? '',
    round: s.round ?? '',
    durationSec: s.durationSec,
    estimatedSec: s.estimatedSec,
    tasks: s.tasks ?? [],
    details: s.details.map((d) => d.name),
    label: isBreak(s.type) ? '' : s.label,
    speech: isBreak(s.type) ? spokenBody(s.speech) : s.speech,
    nextText: s.nextText ?? '',
  };
}

const compiled = compileWorkout(KETTLEBELL_AND_MAT, SEED_EXERCISES);

describe('the built-in workout still matches the original app', () => {
  it('produces the same number of steps', () => {
    expect(compiled.steps).toHaveLength(legacy.steps.length);
  });

  it('produces the same steps, in the same order', () => {
    expect(compiled.steps.map(fromCompiled)).toEqual(legacy.steps.map(fromLegacy));
  });

  it('runs for the same total time', () => {
    expect(compiled.totalSec).toBe(legacy.total);
  });

  it('starts every step at the same moment', () => {
    expect(compiled.cumulativeSec).toEqual(legacy.cum);
  });

  it('divides the progress bar the same way', () => {
    expect(compiled.segments).toEqual(
      legacy.segs.map((s) => ({ phase: s.phase, startSec: s.start, totalSec: s.total })),
    );
  });

  it('can still start from any section', () => {
    const working = (type: string) => !isBreak(type);

    for (let section = 0; section < KETTLEBELL_AND_MAT.sections.length; section++) {
      const run = compileWorkout(KETTLEBELL_AND_MAT, SEED_EXERCISES, {
        fromSectionIndex: section,
      });
      const expected = legacy.steps.filter((s) => s.sec >= section);

      expect(run.steps).toHaveLength(expected.length);
      expect(run.steps.filter((s) => working(s.type)).map((s) => s.title)).toEqual(
        expected.filter((s) => working(s.type)).map((s) => s.title),
      );
    }
  });
});

describe('the one deliberate difference', () => {
  const breakBeforeEndurance = compiled.steps.findIndex(
    (s) => s.hint === 'Switch to your lighter bell.',
  );

  it('makes the pre-endurance break a prep step rather than a trailing rest', () => {
    expect(legacy.steps[breakBeforeEndurance]).toMatchObject({ type: 'rest', phase: 'endurance' });
    expect(compiled.steps[breakBeforeEndurance]).toMatchObject({
      type: 'prep',
      phase: 'endurance',
      durationSec: 15,
    });
  });

  it('announces it as a get-ready rather than a rest', () => {
    expect(compiled.steps[breakBeforeEndurance]?.speech).toBe('Get ready. Next, Round 1 of 4');
  });
});
